version: 0.0
os: linux
files:
  - source: flask_app.zip
    destination: /home/ec2-user/flask-app
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
  ValidateService:
     - location: scripts/health_check.sh
       timeout: 30
